repeat wait() until game:IsLoaded()
loadstring(game:HttpGet("https://raw.githubusercontent.com/XxBoomer/script/main/AllStarTD/Combo%20afk/Teleport.lua", true))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/XxBoomer/script/main/AllStarTD/Combo%20afk/AntiAFK.lua", true))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/XxBoomer/script/main/AllStarTD/Combo%20afk/TimerGUI.lua", true))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/XxBoomer/script/main/AllStarTD/Combo%20afk/autokick24h.lua", true))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/XxBoomer/script/main/AllStarTD/Combo%20afk/webhook.lua", true))()
